name: CI/CD Pipeline

# Disparar o pipeline em push ou pull request na branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar o .NET e restaurar dependências
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies
        run: dotnet restore

      # 3. Build da aplicação
      - name: Build the application
        run: dotnet build --configuration Release --no-restore

      # 4. Run tests
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      # 5. Build da imagem Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/smartcityapi:latest .

      # 6. Login no Docker Hub
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # 7. Push da imagem Docker para o Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/smartcityapi:latest
